module lmp_ipcc_observer
{
  interface IPCCObserver;
};

module lmp_ipcc
{
  interface IPCC
  {
    void destroy();
    void enable();
    void disable();
    void registerObserver(
      in lmp_ipcc_observer::IPCCObserver   observer);
    void deregisterObserver(
      in lmp_ipcc_observer::IPCCObserver   observer);
  };
};
