
#include "lmp_mgtif_node.idl"

module lmp_node_registry
{
  interface NodeRegistry
  {
    void registerNode(
      in lmp_node::Node  aNode);
    void deregisterNode(
      in lmp_node::Node  aNode);
    boolean isNodeRegistered(
      in long  nodeId);
  };
};
