#include "lmp_mgtif_ipcc_observer.idl"

module lmp_ipcc
{
  interface IPCC
  {
    void destroy();
    void enable();
    void disable();
    void registerObserver(
      in IPCCObserver   observer);
    void deregisterObserver(
      in IPCCObserver   observer);
  };
};
