module lmp_ipcc_observer
{
  enum IPCC_State { IPCC_Down, IPCC_ConfSend, IPCC_ConfRecv, IPCC_Active, IPCC_Up, IPCC_GoingDown };

  interface IPCCObserver
  {
    void stateHasChanged(
      in long        localCCId,
      in IPCC_State  newState);
    void peerIpccDiscovered(
      in long  localCCId,
      in long  remoteCCId,
      in long  remoteNodeId);
  };
};
