#include "lmp_mgtif_ipcc_common.idl"

module lmp_ipcc_observer
{
  interface IPCCObserver;
};

module lmp_ipcc
{
  interface IPCC
  {
 	long getLocalCCId();
    long getNodeId();
    lmp_ipcc_common::IPCC_State getState();
 	long getRemoteAddress();
 	short getRemotePortNumber();
    void destroy();
    void enable();
    void disable();
    void registerObserver(
      in lmp_ipcc_observer::IPCCObserver   observer);
    void deregisterObserver(
      in lmp_ipcc_observer::IPCCObserver   observer);
  };
};
